# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10

# Mod Properties
mod_version=1.0.8
maven_group=net.thorminate.hotpotato
archives_base_name=Hot-Potato-1.21.4

# Dependencies
fabric_version=0.115.1+1.21.4
cloth_config_version=17.0.144
mod_menu_version=13.0.1